"""chunk_type as string, drop content_hash

Revision ID: a1c4e7f92b60
Revises: d0371f6b5f55
Create Date: 2026-08-17 00:00:00.000000

Written by hand rather than autogenerated. A column whose *type* changes with
data behind it is one of the cases docs/migrations.md names as one autogenerate
gets wrong - it sees a drop and an add, which is how a conversion silently
becomes data loss.

Two changes, and neither is cosmetic:

  chunk_type stops being a native enum. The values the chunkers actually produce
  do not fit a fixed set: the TypeScript parser emits interface, enum and
  type_alias, and a Jira project defines whatever issue types it likes. Every one
  of those would otherwise cost an ALTER TYPE ... ADD VALUE in its own migration.
  The column stays nullable and stays indexed.

  content_hash comes out. Nothing ever wrote it - the re-ingestion skip it was
  reserved for has not been built - and a column no code touches is one every
  reader has to guess at. It comes back with the code that needs it.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1c4e7f92b60'
down_revision: Union[str, Sequence[str], None] = 'd0371f6b5f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The ten members the type held in the initial schema. Spelled out here because
# both directions need them: upgrade() to name the type it is converting away
# from, downgrade() to build it again.
CHUNK_TYPE_MEMBERS = (
    'FILE',
    'CLASS',
    'METHOD',
    'FUNCTION',
    'ISSUE',
    'PAGE',
    'MESSAGE',
    'EPIC',
    'DOCUMENT',
    'DOCUMENT_SECTION',
)


def upgrade() -> None:
    """Upgrade schema."""
    # Every existing value is already an upper-case name that is valid text, so
    # the USING clause is a plain cast and no row can fail it. ix_chunks_chunk_type
    # needs no attention: PostgreSQL rebuilds an index across ALTER COLUMN TYPE.
    op.alter_column(
        'chunks',
        'chunk_type',
        existing_type=sa.Enum(*CHUNK_TYPE_MEMBERS, name='chunk_type'),
        type_=sa.String(length=255),
        existing_nullable=True,
        postgresql_using='chunk_type::text',
    )

    # The column no longer references it, so the type is now orphaned. Dropped
    # through sa.Enum rather than raw SQL so the statement stays dialect-aware,
    # and checkfirst so a database that never had it is not an error.
    sa.Enum(*CHUNK_TYPE_MEMBERS, name='chunk_type').drop(op.get_bind(), checkfirst=True)

    op.drop_column('chunks', 'content_hash')


def downgrade() -> None:
    """Downgrade schema.

    This fails on any row holding a value outside the ten members above - which
    is every INTERFACE, TYPE_ALIAS or BUG chunk the upgrade makes possible. That
    is the right behaviour: refusing is better than discarding, and the operator
    who wants to go back has to decide what those rows should become first.

    content_hash comes back empty. Nothing ever wrote it, so there is nothing to
    restore, and the column is nullable.
    """
    op.add_column(
        'chunks',
        sa.Column('content_hash', sa.String(length=64), nullable=True),
    )

    chunk_type = sa.Enum(*CHUNK_TYPE_MEMBERS, name='chunk_type')
    chunk_type.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'chunks',
        'chunk_type',
        existing_type=sa.String(length=255),
        type_=chunk_type,
        existing_nullable=True,
        postgresql_using='chunk_type::chunk_type',
    )
