"""initial schema

Revision ID: d0371f6b5f55
Revises: 
Create Date: 2026-08-17 02:01:20.259468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from pgvector.sqlalchemy import VECTOR, Vector

# revision identifiers, used by Alembic.
revision: str = 'd0371f6b5f55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('job_titles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_job_titles_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_titles')),
    sa.UniqueConstraint('department_id', 'name', name=op.f('uq_job_titles_department_id_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('job_title_id', sa.Uuid(), nullable=True),
    sa.Column('application_role', sa.Enum('SUPER_ADMIN', 'HR', 'EMPLOYEE', name='application_role'), server_default='EMPLOYEE', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_titles.id'], name=op.f('fk_users_job_title_id_job_titles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_job_title_id'), 'users', ['job_title_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('original_file_name', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'FAILED', name='document_status'), server_default='UPLOADED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_documents_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_user_id'), 'documents', ['uploaded_by_user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_teams_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_teams_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('department_id', 'name', name=op.f('uq_teams_department_id_name'))
    )
    op.create_index(op.f('ix_teams_created_by_user_id'), 'teams', ['created_by_user_id'], unique=False)
    op.create_table('chat_session_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], name=op.f('fk_chat_session_messages_chat_session_id_chat_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_session_messages'))
    )
    op.create_index(op.f('ix_chat_session_messages_chat_session_id'), 'chat_session_messages', ['chat_session_id'], unique=False)
    op.create_table('source_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('credential_type', sa.Enum('GITHUB', 'JIRA', 'CONFLUENCE', 'SLACK', name='credential_type'), nullable=False),
    sa.Column('secret_reference', sa.String(length=512), nullable=True),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('credential_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_source_credentials_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_credentials'))
    )
    op.create_index(op.f('ix_source_credentials_team_id'), 'source_credentials', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('member_role', sa.Enum('TEAM_LEAD', 'TEAM_MEMBER', name='member_role'), server_default='TEAM_MEMBER', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('user_id', name=op.f('uq_team_members_user_id'))
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('external_data_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('GITHUB', 'JIRA', 'CONFLUENCE', 'SLACK', name='source_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', name='source_status'), server_default='ACTIVE', nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('token', sa.String(length=2048), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_external_data_sources_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['credential_id'], ['source_credentials.id'], name=op.f('fk_external_data_sources_credential_id_source_credentials')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_external_data_sources_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_data_sources'))
    )
    op.create_index(op.f('ix_external_data_sources_created_by_user_id'), 'external_data_sources', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_external_data_sources_credential_id'), 'external_data_sources', ['credential_id'], unique=False)
    op.create_index(op.f('ix_external_data_sources_source_type'), 'external_data_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_external_data_sources_status'), 'external_data_sources', ['status'], unique=False)
    op.create_index(op.f('ix_external_data_sources_team_id'), 'external_data_sources', ['team_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_data_source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('resource_type', sa.Enum('GITHUB_FILE', 'JIRA_ISSUE', 'CONFLUENCE_PAGE', 'SLACK_MESSAGE', 'DOCUMENT', name='resource_type'), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('version_key', sa.String(length=255), nullable=True),
    sa.Column('access_scope', sa.Enum('TEAM', 'DEPARTMENT', 'ORGANIZATION', name='resource_access_scope'), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('resource_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(external_data_source_id IS NULL) <> (document_id IS NULL)', name=op.f('ck_resources_single_origin')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_resources_department_id_departments')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_resources_document_id_documents')),
    sa.ForeignKeyConstraint(['external_data_source_id'], ['external_data_sources.id'], name=op.f('fk_resources_external_data_source_id_external_data_sources')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_resources_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('external_data_source_id', 'external_id', name=op.f('uq_resources_external_data_source_id_external_id'))
    )
    op.create_index(op.f('ix_resources_access_scope'), 'resources', ['access_scope'], unique=False)
    op.create_index(op.f('ix_resources_department_id'), 'resources', ['department_id'], unique=False)
    op.create_index(op.f('ix_resources_document_id'), 'resources', ['document_id'], unique=True)
    op.create_index(op.f('ix_resources_external_id'), 'resources', ['external_id'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_team_id'), 'resources', ['team_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_data_source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='sync_run_status'), server_default='PENDING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resources_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunks_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunks_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunks_deleted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_data_source_id'], ['external_data_sources.id'], name=op.f('fk_sync_runs_external_data_source_id_external_data_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index(op.f('ix_sync_runs_external_data_source_id'), 'sync_runs', ['external_data_source_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_data_source_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Enum('FILE', 'CLASS', 'METHOD', 'FUNCTION', 'ISSUE', 'PAGE', 'MESSAGE', 'EPIC', 'DOCUMENT', 'DOCUMENT_SECTION', name='chunk_type'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('chunk_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('access_scope', sa.Enum('TEAM', 'DEPARTMENT', 'ORGANIZATION', name='resource_access_scope'), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_chunks_department_id_departments')),
    sa.ForeignKeyConstraint(['external_data_source_id', 'external_id'], ['resources.external_data_source_id', 'resources.external_id'], name='fk_chunks_resource'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_chunks_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('external_data_source_id', 'external_id', 'chunk_index', name=op.f('uq_chunks_external_data_source_id_external_id_chunk_index'))
    )
    op.create_index(op.f('ix_chunks_access_scope'), 'chunks', ['access_scope'], unique=False)
    op.create_index(op.f('ix_chunks_chunk_type'), 'chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_chunks_department_id'), 'chunks', ['department_id'], unique=False)
    op.create_index(op.f('ix_chunks_team_id'), 'chunks', ['team_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_message_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('citation_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_session_messages.id'], name=op.f('fk_citations_chat_message_id_chat_session_messages')),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_citations_chunk_id_chunks')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_citations_resource_id_resources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations')),
    sa.UniqueConstraint('chat_message_id', 'citation_order', name=op.f('uq_citations_chat_message_id_citation_order'))
    )
    op.create_index(op.f('ix_citations_chunk_id'), 'citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_citations_resource_id'), 'citations', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_resource_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_chunk_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_chunks_team_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_department_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_chunk_type'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_access_scope'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_external_data_source_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_resources_team_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_external_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_document_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_department_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_access_scope'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_external_data_sources_team_id'), table_name='external_data_sources')
    op.drop_index(op.f('ix_external_data_sources_status'), table_name='external_data_sources')
    op.drop_index(op.f('ix_external_data_sources_source_type'), table_name='external_data_sources')
    op.drop_index(op.f('ix_external_data_sources_credential_id'), table_name='external_data_sources')
    op.drop_index(op.f('ix_external_data_sources_created_by_user_id'), table_name='external_data_sources')
    op.drop_table('external_data_sources')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_source_credentials_team_id'), table_name='source_credentials')
    op.drop_table('source_credentials')
    op.drop_index(op.f('ix_chat_session_messages_chat_session_id'), table_name='chat_session_messages')
    op.drop_table('chat_session_messages')
    op.drop_index(op.f('ix_teams_created_by_user_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_documents_uploaded_by_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_job_title_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('job_titles')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
